### ISSUE TITLE
Error: autoload.php not found

### ISSUE THREAD

**Issue by demircimurat** [Dawnthorn/mysql-concentrator#1]
A required file autoload not found error.. Maybe forgot to publish that file?

**Comment by Dawnthorn** [comment]
The autoload.php file is generated by composer which I failed to mention in the installation docs. Also, the path was wrong. I updated the docs and the paths, and so now if you do:
    `composer`
    `php bin/mysql-concentrator.php -h 127.0.0.1 -p 3306`
It should work.
